apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  namespace: node-app

spec:
  containers:
    - name: node-container
      image: vaibhavchudari/node-app-2
      ports:
        - containerPort: 8000
